## 1. Create a null vector of size 10 but the fifth value which is 1.


In [1]:
import numpy as np 

In [2]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 2. Create a vector with values ranging from 10 to 49.


In [3]:
nd_vector = np.arange(10,50)
nd_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
non_zero = np.nonzero([1,2,0,0,4,0])
non_zero

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.


In [12]:
np.random.seed(0)
random_matrix = np.random.randint(1,1000,(10,10))
random_matrix

array([[685, 560, 630, 193, 836, 764, 708, 360,  10, 724],
       [278, 755, 805, 600,  71, 473, 601, 397, 315, 706],
       [487, 552,  88, 175, 601, 850, 678, 538, 846,  73],
       [778, 917, 116, 977, 756, 710, 848, 432, 449, 851],
       [100, 985, 178, 756, 798, 660, 148, 911, 424, 289],
       [962, 266, 698, 640, 545, 544, 715, 245, 152, 676],
       [511, 460, 883, 184,  29, 803, 129, 129, 933,  54],
       [902, 551, 489, 757, 274, 336, 389, 618,  43, 443],
       [544, 889, 258, 322, 938,  58, 292, 871, 120, 780],
       [431,  83,  92, 897, 399, 612, 566, 909, 634, 939]])

In [13]:
random_matrix.max()

985

In [14]:
random_matrix.min()

10

## 6. Create a random vector of size 30 and find the mean value.

In [19]:
np.random.seed(0)
matrix = np.random.randint(101,300,size=(30))
matrix

array([273, 148, 218, 293, 168, 296, 204, 110, 122, 137, 188, 171, 189,
       241, 159, 294, 140, 188, 275, 189, 182, 266, 126, 178, 173, 110,
       249, 216, 298, 180])

In [20]:
matrix.mean()

199.36666666666667